DATABASE_DEBUG:
    host: "localhost"
    user: "root"
    passwd: "1234"
    db: "LegoSorterDB"
    port: 3306

DATABASE_PROD:
    host: "mysqlserver"
    user: "WebDBUser"
    passwd: "1234"
    db: "LegoSorterDB"
    port: 3306

GOOGLE_DRIVE:
    access_token: "https://help.talend.com/r/Ovc10QFckCdvYbzxTECexA/EoAKa_oFqZFXH0aE0wNbHQ"
    refresh_token: "https://help.talend.com/r/Ovc10QFckCdvYbzxTECexA/EoAKa_oFqZFXH0aE0wNbHQ"